### PR TITLE
Add more linker flags to readme

### PR DESCRIPTION
**Pull request by michaeleisel**
Thanks to @kastiglione for the ideas (from https://github.com/michaeleisel/zld/issues/6). @kastiglione feel free to let me know if this looks reasonable, compact unwind is certainly murky

### CODE REVIEW

**Comment by kastiglione** [comment]
Very well worded! I plan to do more testing of `-no_compact_unwind`, I'll report back on how it goes.

**Comment by kastiglione** [comment]
I had to revert `-no_compact_unwind` from our linker settings, turns out we do have C++ dependencies that I forgot about ([Envoy mobile](https://envoy-mobile.github.io)). I think the description here is still accurate though, our failure was only in C++ code.

**Comment by michaeleisel** [comment]
All good, I think I'll just merge this then. Yeah generally I don't like ObjC exceptions since they (by default) leak memory with ARC, and would like to get C++ devs to come grumbling along by not doing their exceptions. Would be a nice win for app size too. Anyways

**Comment by kastiglione** [comment]
Agreed

**Pull request merged**
