### PR TITLE
add travis config

### PR DESCRIPTION
**Pull request by rmaz**
Adds a basic travis config to build using the Makefile set up in #11.

### CODE REVIEW

**Comment by rmaz** [comment]
@michaeleisel you will need to set up the request hook as described here: https://docs.travis-ci.com/user/tutorial/

**Comment by kastiglione** [comment]
Travis vs GitHub Actions?

**Comment by rmaz** [comment]
Oh, is that the new world? Lets give that a go.

**Comment by kastiglione** [comment]
It was an open question, I haven't yet used GitHub Actions but its looking like the de facto choice.

**Pull request closed without merging**
