### PR TITLE
Use static libraries instead of dynamic

### PR DESCRIPTION
**Pull request by michaeleisel**
The static libs were built using `homebrew install -s`

### CODE REVIEW

**Comment by michaeleisel** [comment]
@kastiglione @rmaz feel free to let me know if there any issues you see

**Comment by rmaz** [comment]
Worth adding the tbb build to the Makefile for easier updating? Otherwise LGTM

**Comment by michaeleisel** [comment]
How would you propose adding it?

**Comment by rmaz** [comment]
Ideally using cmake in a similar fashion to abseil, but looks to be a bit painful on first glance. How does the homebrew build generate its static lib?

**Comment by michaeleisel** [comment]
Here's the output: https://gist.github.com/michaeleisel/ddf5bd1d90f87128cd8c5bd1f912d521

I think I'll just commit the static lib, it may not change for a year or more. Unless you think large-scale orgs would balk at using it for security reasons?

**Comment by rmaz** [comment]
Ja, think its fine for now, just need to make sure they are updated in lockstep

**Pull request merged**
